# Definimos una clase de excepción personalizada para errores de nombre demasiado largo
class LargoExcedidoError(Exception):
    pass

# Definimos una clase de excepción personalizada para errores de subtipo inválido
class SubTipoInvalidoError(Exception):
    pass
